import streamlit as st
import google.generativeai as genai
from fpdf import FPDF
import requests
from bs4 import BeautifulSoup
import io
import time

# -----------------------------------------------------------------------------
# CONFIGURATION
# -----------------------------------------------------------------------------
st.set_page_config(
    page_title="BRAND BIBLE PRO",
    page_icon="💥",
    layout="wide",
    initial_sidebar_state="expanded"
)

# -----------------------------------------------------------------------------
# NEO-BRUTALIST CSS (BOLD, DISTINCT, POP ART)
# -----------------------------------------------------------------------------
st.markdown("""
<style>
    /* IMPORT BOLD FONTS */
    @import url('https://fonts.googleapis.com/css2?family=Space+Grotesk:wght@300;400;700&display=swap');
    
    html, body, [class*="css"] {
        font-family: 'Space Grotesk', sans-serif;
        color: #000;
    }

    /* MAIN BACKGROUND */
    .stApp {
        background-color: #FFFCF2; /* Warm Paper Color */
        background-image: radial-gradient(#000 1px, transparent 1px);
        background-size: 20px 20px; /* Dot pattern to prove it loaded */
    }

    /* HIDE DEFAULT HEADER */
    header {visibility: hidden;}
    footer {visibility: hidden;}

    /* INPUT FIELDS - HARD BORDERS */
    .stTextInput input, .stTextArea textarea, .stSelectbox div[data-baseweb="select"] {
        background-color: #fff !important;
        border: 3px solid #000 !important;
        border-radius: 0px !important;
        box-shadow: 4px 4px 0px #000 !important;
        color: #000 !important;
        font-weight: 600;
    }
    
    /* SIDEBAR - BOLD */
    section[data-testid="stSidebar"] {
        background-color: #fff;
        border-right: 3px solid #000;
    }
    
    /* BUTTONS - POP ART STYLE */
    div.stButton > button {
        background-color: #FF9F1C; /* Bright Orange */
        color: #000;
        border: 3px solid #000;
        border-radius: 0px;
        font-weight: 800;
        text-transform: uppercase;
        box-shadow: 5px 5px 0px #000;
        transition: all 0.1s;
    }
    div.stButton > button:hover {
        transform: translate(-2px, -2px);
        box-shadow: 7px 7px 0px #000;
        background-color: #FFBF69;
        color: #000;
        border-color: #000;
    }
    div.stButton > button:active {
        transform: translate(2px, 2px);
        box-shadow: 1px 1px 0px #000;
    }

    /* HERO SECTION */
    .hero-box {
        background-color: #2EC4B6; /* Tiffany Blue */
        border: 4px solid #000;
        box-shadow: 8px 8px 0px #000;
        padding: 3rem;
        margin-bottom: 3rem;
    }
    .hero-title {
        font-size: 4rem;
        font-weight: 900;
        text-transform: uppercase;
        line-height: 0.9;
        margin-bottom: 1rem;
        color: #fff;
        text-shadow: 4px 4px 0px #000;
    }

    /* CARDS */
    .feature-card {
        background: #fff;
        border: 3px solid #000;
        padding: 1.5rem;
        margin-bottom: 1rem;
        box-shadow: 6px 6px 0px #000;
    }
    
    /* ACCORDIONS */
    .stExpander {
        border: 3px solid #000 !important;
        border-radius: 0px !important;
        box-shadow: 4px 4px 0px #000 !important;
        background-color: #fff !important;
    }
</style>
""", unsafe_allow_html=True)

# -----------------------------------------------------------------------------
# HELPER FUNCTIONS
# -----------------------------------------------------------------------------

def sanitize_text_for_pdf(text):
    replacements = {
        '\u2018': "'", '\u2019': "'", '\u201c': '"', '\u201d': '"',
        '\u2013': '-', '\u2014': '--', '\u2026': '...', '\u2022': '*',
        '—': '--', '’': "'", '“': '"', '”': '"'
    }
    for k, v in replacements.items():
        text = text.replace(k, v)
    return text.encode('latin-1', 'ignore').decode('latin-1')

def scrape_website_text(url):
    if not url: return None
    try:
        headers = {'User-Agent': 'Mozilla/5.0'}
        response = requests.get(url, headers=headers, timeout=10)
        response.raise_for_status()
        soup = BeautifulSoup(response.content, 'html.parser')
        for script in soup(["script", "style", "nav", "footer"]): script.extract()
        text = soup.get_text(separator=' ')
        return text[:4000]
    except Exception: return None

def create_pdf(content, company_name):
    class PDF(FPDF):
        def header(self):
            self.set_font('Arial', 'B', 16)
            self.cell(0, 10, f'{company_name.upper()} // BRAND BIBLE', 0, 1, 'C')
            self.ln(5)
            self.set_line_width(1)
            self.line(10, 25, 200, 25)
            self.ln(10)
        def footer(self):
            self.set_y(-15)
            self.set_font('Arial', 'B', 8)
            self.cell(0, 10, 'GENERATED BY STRATEGY ENGINE', 0, 0, 'C')

    pdf = PDF()
    pdf.add_page()
    pdf.set_auto_page_break(auto=True, margin=20)
    pdf.set_text_color(0, 0, 0)
    
    lines = content.split('\n')
    for line in lines:
        s_line = sanitize_text_for_pdf(line)
        if line.startswith('###') or line.startswith('**'):
            pdf.ln(5)
            pdf.set_font("Arial", 'B', 12)
            pdf.multi_cell(0, 8, s_line.replace('#', '').replace('*', '').strip())
        elif line.startswith('##'):
            pdf.ln(10)
            pdf.set_font("Arial", 'B', 20)
            pdf.set_fill_color(0, 0, 0)
            pdf.set_text_color(255, 255, 255)
            pdf.cell(0, 12, f"  {s_line.replace('#', '').strip().upper()}  ", 0, 1, 'L', True)
            pdf.set_text_color(0, 0, 0)
            pdf.ln(5)
        elif line.startswith('#'):
            pdf.add_page()
            pdf.set_font("Arial", 'B', 30)
            pdf.multi_cell(0, 20, s_line.replace('#', '').strip().upper(), align='C')
            pdf.ln(10)
        else:
            pdf.set_font("Arial", size=11)
            pdf.multi_cell(0, 6, s_line)
            
    return pdf.output(dest='S').encode('latin-1')

# -----------------------------------------------------------------------------
# SESSION STATE
# -----------------------------------------------------------------------------
if 'payment_status' not in st.session_state: st.session_state['payment_status'] = False
if 'generated_bible' not in st.session_state: st.session_state['generated_bible'] = None

# -----------------------------------------------------------------------------
# SIDEBAR
# -----------------------------------------------------------------------------
with st.sidebar:
    st.markdown("## ⚙️ CONTROLS")
    api_key = st.text_input("GOOGLE AI KEY", type="password")
    
    with st.expander("1. WHO ARE YOU?", expanded=True):
        company_name = st.text_input("COMPANY NAME", "Acme Corp")
        industry = st.text_input("INDUSTRY", "Tech")
        url = st.text_input("WEBSITE URL")

    with st.expander("2. THE STRATEGY"):
        enemy = st.text_input("THE ENEMY", "Boredom")
        origin_story = st.text_area("ORIGIN STORY")
        one_thing = st.text_input("ONE THING")

    with st.expander("3. THE VIBE"):
        fears_desires = st.text_area("FEARS / DESIRES")
        archetype = st.selectbox("ARCHETYPE", ["Rebel", "Magician", "Hero", "Lover", "Sage", "Creator", "Ruler"])
        feeling = st.text_input("FEELING")
        aesthetic = st.selectbox("STYLE", ["Swiss", "Brutalist", "Luxury", "Tech"])
        voice_match = st.text_input("VOICE MATCH")

# -----------------------------------------------------------------------------
# MAIN LAYOUT
# -----------------------------------------------------------------------------

# HERO
st.markdown("""
<div class="hero-box">
    <div class="hero-title">Brand Bible<br>Generator</div>
    <div style="font-size: 1.5rem; font-weight: 700;">
        Create a world-class identity system in 10 seconds.
    </div>
</div>
""", unsafe_allow_html=True)

col1, col2 = st.columns([2, 1], gap="large")

with col1:
    if not st.session_state['payment_status']:
        st.markdown("""
        <div class="feature-card">
            <h3>📂 1. The North Star</h3>
            <p>Mission. Vision. Manifesto.</p>
        </div>
        <div class="feature-card">
            <h3>🗣️ 2. The Voice</h3>
            <p>Taglines. Hooks. Vocabulary.</p>
        </div>
        <div class="feature-card">
            <h3>🎨 3. The Look</h3>
            <p>Logo briefs. Typography. Art Direction.</p>
        </div>
        """, unsafe_allow_html=True)

        st.markdown("### 🔓 UNLOCK ACCESS")
        pay_btn = st.button("PROCESS PAYMENT ($99)", type="primary")

        if pay_btn:
            with st.spinner("VERIFYING..."):
                time.sleep(1)
                st.session_state['payment_status'] = True
                st.rerun()

    else:
        st.success("ACCESS UNLOCKED.")
        if st.button("GENERATE BIBLE"):
            if not api_key:
                st.error("MISSING API KEY")
            else:
                genai.configure(api_key=api_key)
                with st.spinner("BUILDING STRATEGY..."):
                    web_context = ""
                    if url:
                        web_data = scrape_website_text(url)
                        if web_data: web_context = f"WEB DATA: {web_data}"

                    prompt = f"""
                    Role: Expert Brand Strategist.
                    Task: Create a Brand Bible for {company_name}.
                    Inputs: {industry}, Enemy: {enemy}, Origin: {origin_story}, Value: {one_thing}, 
                    Psychology: {fears_desires}, Archetype: {archetype}, Style: {aesthetic}.
                    {web_context}
                    
                    Sections (Markdown):
                    # BRAND BIBLE: {company_name}
                    ## 1. MANIFESTO
                    ## 2. PERSONA
                    ## 3. VERBAL IDENTITY
                    ## 4. VISUAL IDENTITY
                    """
                    try:
                        model = genai.GenerativeModel('gemini-1.5-flash')
                        resp = model.generate_content(prompt)
                        st.session_state['generated_bible'] = resp.text
                    except Exception as e:
                        st.error(f"Error: {e}")

        if st.session_state['generated_bible']:
            st.markdown(st.session_state['generated_bible'])
            pdf = create_pdf(st.session_state['generated_bible'], company_name)
            st.download_button("DOWNLOAD PDF", pdf, "bible.pdf", "application/pdf")

with col2:
    if not st.session_state['payment_status']:
        st.markdown("""
        <div style="background: #CBF3F0; border: 3px solid #000; padding: 20px; box-shadow: 6px 6px 0px #000;">
            <strong>RECENT JOBS</strong>
            <hr style="border-top: 2px solid #000;">
            <p>Nike (Rebrand)</p>
            <p>Liquid Death (Strategy)</p>
            <p>Linear (Voice)</p>
        </div>
        """, unsafe_allow_html=True)
